CREATE TABLE STATUS (
  STATUS_ID int(11) NOT NULL,
  DESCRIPTION varchar(45) DEFAULT NULL,
  COMPONENT varchar(45) DEFAULT NULL,
  INSERT_DATE datetime DEFAULT NULL,
  PRIMARY KEY (STATUS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE RESPONSE_TYPE (
  RESPONSE_TYPE_ID int(11) NOT NULL,
  PRIMARY KEY (RESPONSE_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE TRANSACTION_TYPE (
  TRX_TYPE_ID int(11) NOT NULL,
  PRIMARY KEY (TRX_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
