CREATE TABLE STATUS (
  STATUS_ID INT(11) NOT NULL,
  DESCRIPTION VARCHAR(45) DEFAULT NULL,
  COMPONENT VARCHAR(45) DEFAULT NULL,
  INSERT_DATE DATETIME DEFAULT NULL,
  PRIMARY KEY (STATUS_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


CREATE TABLE RESPONSE_TYPE (
  RESPONSE_TYPE_ID INT(11) NOT NULL,
  PRIMARY KEY (RESPONSE_TYPE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;


CREATE TABLE TRANSACTION_TYPE (
  TRX_TYPE_ID INT(11) NOT NULL,
  PRIMARY KEY (TRX_TYPE_ID)
) ENGINE=INNODB DEFAULT CHARSET=UTF8;
