---User management
INSERT INTO STATUS VALUES (1,'CREATED','USER MANAGEMENT',NOW());
INSERT INTO STATUS VALUES (2,'ACTIVE','USER MANAGEMENT',NOW());
INSERT INTO STATUS VALUES (3,'INACTIVE','USER MANAGEMENT',NOW());
INSERT INTO STATUS VALUES (4,'LOCKED','USER MANAGEMENT',NOW());
---Role management
INSERT INTO STATUS VALUES (11,'ACTIVE','ROLE MANAGEMENT',NOW());
INSERT INTO STATUS VALUES (12,'INACTIVE ROLE','ROLE MANAGEMENT',NOW());
INSERT INTO STATUS VALUES (13,'LOCKED ROLE','ROLE MANAGEMENT',NOW());


INSERT INTO RESPONSE_TYPE VALUES (0);
INSERT INTO RESPONSE_TYPE VALUES (1);
INSERT INTO RESPONSE_TYPE VALUES (2);
INSERT INTO RESPONSE_TYPE VALUES (3);

INSERT INTO TRANSACTION_TYPE VALUES (0);
INSERT INTO TRANSACTION_TYPE VALUES (1);
INSERT INTO TRANSACTION_TYPE VALUES (2);
INSERT INTO TRANSACTION_TYPE VALUES (3);
INSERT INTO TRANSACTION_TYPE VALUES (4);