INSERT INTO STATUS VALUES (1,'CREATE USER','USER MANAGEMENT',NOW());
INSERT INTO STATUS VALUES (2,'UPDATE USER','USER MANAGEMENT',NOW());

INSERT INTO STATUS VALUES (11,'CREATE ROLE','ROLE MANAGEMENT',NOW());
INSERT INTO STATUS VALUES (12,'UPDATE ROLE','ROLE MANAGEMENT',NOW());


INSERT INTO RESPONSE_TYPE VALUES (0);
INSERT INTO RESPONSE_TYPE VALUES (1);
INSERT INTO RESPONSE_TYPE VALUES (2);
INSERT INTO RESPONSE_TYPE VALUES (3);

INSERT INTO TRANSACTION_TYPE VALUES (0);
INSERT INTO TRANSACTION_TYPE VALUES (1);
INSERT INTO TRANSACTION_TYPE VALUES (2);
INSERT INTO TRANSACTION_TYPE VALUES (3);
INSERT INTO TRANSACTION_TYPE VALUES (4);