CREATE TABLE PRIVILEGES (
  PRIVILEGE_ID int(11) NOT NULL,
  OPERATION varchar(45) DEFAULT NULL COMMENT '				',
  COMPONENT varchar(45) DEFAULT NULL,
  DESCRIPTION varchar(200) DEFAULT NULL COMMENT '			',
  EFFECTIVE_DATE datetime DEFAULT NULL COMMENT '		',
  EXPIRED_DATE datetime DEFAULT NULL,
  STATUS_ID int(11) NOT NULL,
  INSERT_DATE datetime DEFAULT NULL,
  MOD_DATE varchar(45) DEFAULT NULL,
  PRIMARY KEY (PRIVILEGE_ID),
  KEY FK_PRI_STATUS_ID_IDX (STATUS_ID),
  CONSTRAINT FK_PRI_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES STATUS (STATUS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE USER_TYPES (
  USER_TYPE_ID int(11) NOT NULL,
  TYPE_NAME varchar(45) DEFAULT NULL,
  TYPE_DESCR varchar(200) DEFAULT NULL,
  INSERT_DATE datetime DEFAULT NULL,
  PRIMARY KEY (USER_TYPE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE USER_TYPE_PRIVILEGES (
  USER_TYPE_ID int(11) NOT NULL,
  PRILIVEGE_ID int(11) NOT NULL,
  EFFECTIVE_DATE datetime DEFAULT NULL,
  END_DATE datetime DEFAULT NULL,
  INSERT_DATE datetime DEFAULT NULL,
  MOD_DATE datetime DEFAULT NULL,
  PRIMARY KEY (USER_TYPE_ID,PRILIVEGE_ID),
  KEY FK_USER_TYPE_PRIV_IDX (PRILIVEGE_ID),
  CONSTRAINT FK_USER_TYPE_PRIV FOREIGN KEY (PRILIVEGE_ID) REFERENCES PRIVILEGES (PRIVILEGE_ID) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT FK_USER_TYPE_TBL FOREIGN KEY (USER_TYPE_ID) REFERENCES USER_TYPES (USER_TYPE_ID) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE ROLE (
  ROLE_ID int(11) NOT NULL,
  ROLE_NAME varchar(45) NOT NULL,
  ROLE_DESCR varchar(200) DEFAULT NULL,
  USER_TYPE_ID int(11) DEFAULT NULL,
  STATUS_ID int(11) DEFAULT NULL,
  INSERT_DATE datetime DEFAULT NULL COMMENT '		',
  MOD_DATE datetime DEFAULT NULL,
  PRIMARY KEY (ROLE_ID),
  KEY FK_ROLE_STATUS_ID_IDX (STATUS_ID),
  KEY FK_USER_TYPE_ROLE_IDX (USER_TYPE_ID),
  CONSTRAINT FK_ROLE_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES STATUS (STATUS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_USER_TYPE_ROLE FOREIGN KEY (USER_TYPE_ID) REFERENCES USER_TYPES (USER_TYPE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE ROLE_PRIVILEGES (
  ROLE_ID int(11) NOT NULL,
  PRIVILEGE_ID int(11) NOT NULL,
  EFFECTIVE_DATE datetime DEFAULT NULL,
  END_DATE datetime DEFAULT NULL,
  INSERT_DATE datetime DEFAULT NULL,
  MOD_DATE datetime DEFAULT NULL,
  PRIMARY KEY (ROLE_ID,PRIVILEGE_ID),
  KEY FK_ROLE_PRIV_ID_IDX (PRIVILEGE_ID),
  CONSTRAINT FK_ROLE_ID_PRIV FOREIGN KEY (ROLE_ID) REFERENCES ROLE (ROLE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_ROLE_PRIV_ID FOREIGN KEY (PRIVILEGE_ID) REFERENCES PRIVILEGES (PRIVILEGE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE USERS (
  USER_ID int(11) NOT NULL,
  LOGIN_NAME varchar(45) DEFAULT NULL,
  FIRST_NAME varchar(45) DEFAULT NULL,
  LAST_NAME varchar(45) DEFAULT NULL,
  EFFECTIVE_DATE datetime DEFAULT NULL,
  PASSWORD varchar(200) DEFAULT NULL,
  PASSWORD1 varchar(200) DEFAULT NULL,
  PASSWORD2 varchar(200) DEFAULT NULL,
  BAD_PWD_CNT varchar(45) DEFAULT NULL,
  USER_STATUS_ID int(11) DEFAULT NULL,
  USER_TYPE_ID int(11) DEFAULT NULL,
  INSERT_DATE datetime DEFAULT NULL,
  PRIMARY KEY (USER_ID),
  KEY FK_USER_STATUS_ID_IDX (USER_STATUS_ID),
  KEY FK_USER_TYPE_ID_IDX (USER_TYPE_ID),
  CONSTRAINT FK_USER_STATUS_ID FOREIGN KEY (USER_STATUS_ID) REFERENCES STATUS (STATUS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_USER_TYPE_ID FOREIGN KEY (USER_TYPE_ID) REFERENCES USER_TYPES (USER_TYPE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
