CREATE TABLE IF NOT EXISTS RESOURCE_ROLE (
  ID          INT         NOT NULL,
  DESCRIPTION VARCHAR(45) NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS SKILL_LEVEL (
  ID         INT          NOT NULL,
  CODE       VARCHAR(1)   NOT NULL,
  SHORT_DESC VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS SKILLS_DOMAIN (
  DOMAIN_ID        INT          NOT NULL,
  PARENT_DOMAIN_ID INT          NOT NULL,
  CODE             VARCHAR(50)  NOT NULL,
  SHORT_DESC       VARCHAR(200) NOT NULL,
  PRIMARY KEY (DOMAIN_ID)
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;


CREATE TABLE IF NOT EXISTS SKILLS (
  SKILL_ID   INT          NOT NULL,
  DOMAIN_ID  INT          NOT NULL,
  SKILL_DESC VARCHAR(200) NOT NULL,
  PRIMARY KEY (SKILL_ID),
  INDEX FK_SKILL_DOMAIN_ID_IDX (DOMAIN_ID ASC),
  CONSTRAINT FK_SKILL_DOMAIN_ID
  FOREIGN KEY (DOMAIN_ID)
  REFERENCES SKILLS_DOMAIN (DOMAIN_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS RESOURCES (
  XEROX_CID    VARCHAR(20) NOT NULL,
  COGNIZANT_ID VARCHAR(45) NOT NULL,
  NAME         VARCHAR(45) NOT NULL,
  ROLE_ID      INT         NOT NULL,
  PRIMARY KEY (XEROX_CID),
  INDEX FK_ROLE_ID_IDX (ROLE_ID ASC),
  CONSTRAINT FK_ROLE_ID
  FOREIGN KEY (ROLE_ID)
  REFERENCES RESOURCE_ROLE (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;

CREATE TABLE IF NOT EXISTS RESOURCE_SKILLS (
  RESOURCE_ID    VARCHAR(20) NOT NULL
  COMMENT '	',
  SKILL_ID       INT         NOT NULL,
  SKILL_LEVEL_ID INT         NOT NULL,
  PRIMARY KEY (RESOURCE_ID),
  INDEX FK_SKILL_ID_IDX (SKILL_ID ASC),
  INDEX FK_SKILL_LEVEL_ID_IDX (SKILL_LEVEL_ID ASC),
  CONSTRAINT FK_RESOURCE_ID
  FOREIGN KEY (RESOURCE_ID)
  REFERENCES RESOURCES (XEROX_CID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_SKILL_ID
  FOREIGN KEY (SKILL_ID)
  REFERENCES SKILLS (SKILL_ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT FK_SKILL_LEVEL_ID
  FOREIGN KEY (SKILL_LEVEL_ID)
  REFERENCES SKILL_LEVEL (ID)
    ON DELETE CASCADE
    ON UPDATE CASCADE
)
  ENGINE = INNODB
  DEFAULT CHARSET = UTF8;