INSERT INTO RESOURCE_ROLE VALUES (1,'DEV');
INSERT INTO RESOURCE_ROLE VALUES (2,'QA');

INSERT INTO SKILL_LEVEL VALUES (1,'A','EXPERT');
INSERT INTO SKILL_LEVEL VALUES (2,'B','GOOD');
INSERT INTO SKILL_LEVEL VALUES (3,'C','MIDDLE');
INSERT INTO SKILL_LEVEL VALUES (4,'D','LOW');
INSERT INTO SKILL_LEVEL VALUES (5,'E','UNKNOWN');

--insert into SKILLS values ();

